export enum MANGA {
  REQUEST_RECENT = 'REQUEST_RECENT',
  RECEIVED_RECENT = 'RECEIVED_RECENT',


  REQUEST_MY = 'REQUEST_MY',
  RECEIVED_MY = 'RECEIVED_MY',


  RECEIVED_INFO = "RECEIVED_INFO",
  RECEIVED_INFO_ERROR = "RECEIVED_INFO_ERROR",

}


export enum USER {
  REQUEST_USER_INFO = 'REQUEST_USER_INFO',
  RECEIVED_USER_INFO = 'RECEIVED_USER_INFO',


  SET_FAVORITE = 'SET_FAVORITE',
  UNSET_FAVORITE = 'UNSET_FAVORITE',


  POPULATE_FAVORITE = 'POPULATE_FAVORITE',



  SET_USER = 'SET_USER',
  SET_TOKEN = 'SET_TOKEN',
}


export enum APP_INTERNAL {
  UPDATE_CONNECTIVITY = 'UPDATE_CONNECTIVITY',
  USE_DARK_THEME = 'USE_DARK_THEME',


  INITIALIZING = 'INITIALIZING',
  INITIALIZED = 'INITIALIZED',

}
